import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class AppointmentCreate {
  @ApiProperty()
  patient_id: string;
  @ApiProperty()
  date_time: Date;
  @ApiProperty()
  duration: string;
  @ApiProperty()
  status: string;
}

export class Appointment {
  @ApiProperty()
  id: number;
  @ApiProperty()
  patient_id: string;
  @ApiProperty()
  date_time: Date;
  @ApiProperty()
  duration: string;
  @ApiProperty()
  status: string;
}
